### PR TITLE
Fix denials

### PR DESCRIPTION
**Pull request by unclamped**

### CODE REVIEW

**Comment by SH4ND** [comment]
@unclamped

**Comment by SH4ND** [comment]
@SH4ND Pretinho ajudando nas denials

**Comment by menorziin** [comment]
KKKKKKKKKKKK

**Comment by menorziin** [comment]
Shand queima

**Comment by SH4ND** [comment]
@SH4ND Bro, make a pull request on the common tree

**Comment by unclamped** [comment]
what the fuck are you talking about

**Comment by SH4ND** [comment]
Common trees pull request wen

**Pull request closed without merging**
